a = input('문자열: ')
print(f'대문자 {a.upper()}')
print(f'소문자 {a.lower()}')
print(f'문자열 길이 {len(a)}')
print(f'공백으로 분리: {a.split()}')
print(f'문자로 분리: {a.split(".")}')
print(f'o의 위치: {a.find("o")}')
print(f'o의 개수: {a.count("o")}')
print(f'pyhton을 Ai로 바꾸기: {a.replace("python", "AI")}')